name: Deploy Azure Resource on Cloud Using Terraform

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        working-directory: ./terraform-config
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform-config
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform-config
        run: terraform apply -auto-approve
