name: deploy azure resource on cloude using terraform 

on:
 push:
   branches:
      - main  
permissions:
  id-token: write
  contents: read        

     

jobs: 
    terraform:
        runs-on: ubuntu-latest
        steps:
          - name: Checkuot code
            uses: actions/checkout@v4
          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3    
          
          - name: Login to Azure
            uses: azure/login@v1
            with:
              client-id: ${{ secrets.APPLICATION_CLIENT_ID }}
              tenant-id: ${{ secrets.DIRECTORY_TENANT_ID }}
              subscription-id: ${{ secrets.SUBSCRIPTION }}
              client-secret: ${{ secrets.SECRETS_VALUE }}
               
          - name: Terraform Init
            working-directory: ./terraform-config
            run: terraform init
            
          - name: Terraform plan
            working-directory: ./terraform-config
            run: terraform plan  

          - name: Terraform Apply
            working-directory: ./terraform-config
            run: terraform apply -auto-approve  